export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESFULLY = 'ADD_PRODUCT_SUCCESFULLY'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_SUCCESFULLY = 'GET_PRODUCTS_SUCCESFULLY'
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR'


export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESFULLY = 'DELETE_PRODUCT_SUCCESFULLY'
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR'

export const GET_EDIT_PRODUCT = 'GET_EDIT_PRODUCT'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESFULLY = 'EDIT_PRODUCT_SUCCESFULLY'
export const EDIT_PRODUCT_ERROR = 'EDIT_PRODUCT_ERROR'

export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALTER'